// Generated by scripts/sync_models.py — DO NOT EDIT MANUALLY.
// Re-run `make sync-models` after changing any file in backend/app/schemas/.
//
// JSONDecoder setup required in your app (BackendAPIService or a shared decoder):
//   decoder.dateDecodingStrategy = .iso8601
//   (CodingKeys handle snake_case → camelCase; no keyDecodingStrategy override needed)

import Foundation

/// POST /me/notes request body.
struct NoteIn: Codable, Equatable {
    let title: String
    let body: String?
}

/// Auto-generated from `NoteOut` (backend/app/schemas).
struct NoteOut: Codable, Equatable {
    let id: UUID
    let userId: UUID
    let title: String
    let body: String?
    let createdAt: Date
    let updatedAt: Date

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case title
        case body
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}

/// PATCH /me/notes/{id} request body — all fields optional (partial update).
struct NoteUpdate: Codable, Equatable {
    let title: String?
    let body: String?
}

/// Auto-generated from `ProfileOut` (backend/app/schemas).
struct ProfileOut: Codable, Equatable {
    let id: UUID
    let displayName: String?
    let avatarUrl: String?
    let createdAt: Date
    let isPro: Bool?

    enum CodingKeys: String, CodingKey {
        case id
        case displayName = "display_name"
        case avatarUrl = "avatar_url"
        case createdAt = "created_at"
        case isPro = "is_pro"
    }
}

/// PATCH /me/profile request body — all fields optional (partial update).
struct ProfileUpdate: Codable, Equatable {
    let displayName: String?
    let avatarUrl: String?

    enum CodingKeys: String, CodingKey {
        case displayName = "display_name"
        case avatarUrl = "avatar_url"
    }
}

/// Auth token pair returned by register, login, and refresh endpoints.
struct TokenResponse: Codable, Equatable {
    let accessToken: String
    let refreshToken: String
    let tokenType: String?

    enum CodingKeys: String, CodingKey {
        case accessToken = "access_token"
        case refreshToken = "refresh_token"
        case tokenType = "token_type"
    }
}
